basePath: /api/v1
definitions:
  handler.HealthcheckResponse:
    properties:
      status:
        type: string
      version:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Gateway for the Logistics Services API platform
  title: Logistics Services API Gateway
  version: 1.0.0
paths:
  /health:
    get:
      description: Returns service health check response
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.HealthcheckResponse'
      summary: Health check
      tags:
      - system
    head:
      description: Returns service health check response
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.HealthcheckResponse'
      summary: Health check
      tags:
      - system
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
