// Package shipment Code generated by swaggo/swag. DO NOT EDIT
package shipment

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns service health check response",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.HealthcheckResponse"
                        }
                    }
                }
            },
            "head": {
                "description": "Returns service health check response",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.HealthcheckResponse"
                        }
                    }
                }
            }
        },
        "/shipments": {
            "get": {
                "description": "Returns a list of shipments",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shipment"
                ],
                "summary": "Get Shipments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.Shipment"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new shipment",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shipment"
                ],
                "summary": "Create Shipment",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.Shipment"
                        }
                    }
                }
            }
        },
        "/shipments/:id": {
            "put": {
                "description": "Update a shipment by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shipment"
                ],
                "summary": "Update Shipment by a given ID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Shipment"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a shipment by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shipment"
                ],
                "summary": "Delete Shipment by a given ID",
                "responses": {
                    "202": {
                        "description": "Accepted"
                    }
                }
            }
        },
        "/shipments/{id}": {
            "get": {
                "description": "Get a shipment by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shipment"
                ],
                "summary": "Get Shipment by a given ID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Shipment"
                        }
                    }
                }
            }
        },
        "/shipments/{id}/status": {
            "get": {
                "description": "Get the status of a shipment by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shipment"
                ],
                "summary": "Get Shipment Status by a given ID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Shipment"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.HealthcheckResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "handler.Shipment": {
            "type": "object"
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Shipment Service",
	Description:      "Shipment Service for the Logistics Services API platform",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
