basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: API Gateway for the Logistics Services API platform
  title: Logistics Services API Gateway
  version: 1.0.0
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
