name: logistics

services:
  gateway:
    build:
      context: ..
      dockerfile: manifests/Dockerfile
      args:
        SERVICE: gateway
    ports:
      - "8080:8080"
  shipment:
    build:
      context: ..
      dockerfile: manifests/Dockerfile
      args:
        SERVICE: shipment
    ports:
      - "8081:8081"
  inventory:
    build:
      context: ..
      dockerfile: manifests/Dockerfile
      args:
        SERVICE: inventory
    ports:
      - "8082:8082"
  telemetry:
    build:
      context: ..
      dockerfile: manifests/Dockerfile
      args:
        SERVICE: telemetry
    ports:
      - "8083:8083"
